name: beep-env
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.1.243
  - pillow=8.2.0
  - pip=21.1.1
  - python=3.8.10
  - setproctitle=1.2.2
  - pip:
     - ipykernel==5.5.5
     - numpy==1.20.2
     - nltk==3.6.2
     - jupyter
     - torch==1.7.1
     - scikit_learn==1.0.2
     - scispacy==0.4.0
     - transformers==4.1.1
     - ray==1.3.0
     - ray[tune]
     - protobuf==3.20.3
     - pandas
     - biopython


